on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - mainname: Git Practice

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show project information
        run: |
          echo "AWS Cloud Engineer Project"
          echo "GitHub Actions is working"
          git --version
